### ISSUE TITLE
Issue with wbstats 1.0.1 when using RStudio Version 1.3.1073

### ISSUE THREAD

**Issue by aratsimbaharison** [gshs-ornl/wbstats#25]
I used the older version of wbstats with older versions of RStudio and they worked well together. However, when I upgraded both recently, I got the following error message:
Error: package or namespace load failed for ‘wbstats’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): namespace ‘rlang’ 0.4.6 is already loaded, but >= 0.4.7 is required

Could you please help me to resolve this issue because I am really stuck? I cannot go back to the old versions of wbstats and RStudio.

Thank you!

**Comment by jpiburn** [comment]
Hi sorry for the delay.. I've ran into issues with `rlang` as well, I think it is a common source of install pains. What has worked for me is making sure that none of the packages from the  `tidyverse` ecosystem are loaded in the namespace (the latest release of `dplyr`  which wbstats uses has the dependency of `rlang >= 0.4.7`),  so a fresh R session or `unloadNamespace('tidyverse')` and then `remove.packages('rlang')`. Then run `install.packages('rlang')` separately. Then you should be able to `install.packages('wbstats')`.

good luck. Let me know if this works. 


```
unloadNamespace('tidyverse') # or any other tidyverse packages, dplyr, etc.
remove.packages('rlang')
install.packages('rlang')
install.packages('wbstats')
```

**Comment by aratsimbaharison** [comment]
Hi Jesse,

After two attempts, it worked!

Thank you so much!

Adrien Ratsimbaharison, PhD
Professor of Political Science
Benedict College
Columbia, SC 29204
Phone: 803-705-4315

*Recent publication*:
https://www.amazon.com/Political-Crisis-March-2009-Madagascar/dp/144227235X/ref=sr_1_1?ie=UTF8&qid=1520535574&sr=8-1&keywords=ratsimbaharison
